import { Providers } from "@/redux/provider";
import "./globals.css";
import { Inter, Raleway, Bitter, Brygada_1918, Changa } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const bitter = Bitter({
  subsets: ["latin"],
  variable: "--font-bitter",
});
const paragraph = Brygada_1918({
  subsets: ["latin"],
  variable: "--font-paragraph",
});
const title = Changa({
  subsets: ["latin"],
  variable: "--font-title",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${inter.variable} ${title.variable} ${paragraph.variable} ${bitter.variable}`}
    >
      <body className="p-0 m-0 bg-slate-200/80">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
